package org.policetracks.android.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here

// KEEP INCLUDES END
/**
 * Entity mapped to table "DAY".
 */
@Entity
public class Day {

    @Id
    private Long id;

    @NotNull
    private String description;
    private Long from;
    private Long to;

    @Generated(hash = 406145378)
    public Day(Long id, @NotNull String description, Long from, Long to) {
        this.id = id;
        this.description = description;
        this.from = from;
        this.to = to;
    }

    @Generated(hash = 866989762)
    public Day() {
    }

    public Day(Long id) {
        this.id = id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getDescription() {
        return description;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDescription(@NotNull String description) {
        this.description = description;
    }


    public Long getFrom() {
        return from;
    }

    public void setFrom(Long from) {
        this.from = from;
    }

    public Long getTo() {
        return to;
    }

    public void setTo(Long to) {
        this.to = to;
    }

    public void setDefaults() {
    }
}
