package org.owntracks.android.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import android.location.Location;

import java.util.Calendar;
import java.util.Date;
// KEEP INCLUDES END
/**
 * Entity mapped to table "INTERVENTION".
 */
@Entity
public class Intervention {

    @Id
    private Long id;

    @NotNull
    private String description;
    private Long from;
    private Long to;
    private String ivtype;

    @Generated(hash = 29317382)
    public Intervention(Long id, @NotNull String description, Long from, Long to, String ivtype) {
        this.id = id;
        this.description = description;
        this.from = from;
        this.to = to;
        this.ivtype = ivtype;
    }

    @Generated(hash = 768626443)
    public Intervention() {
    }

    public Intervention(Long id) {
        this.id = id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIvtype() {
        return ivtype;
    }

    public void setIvtype(String ivtype) {
        this.ivtype = ivtype;
    }

    @NotNull
    public String getDescription() {
        return description;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDescription(@NotNull String description) {
        this.description = description;
    }

    public Long getFrom() {
        return from;
    }

    public void setFrom(Long from) {
        this.from = from;
    }

    public Long getTo() {
        return to;
    }

    public void setTo(Long to) {
        this.to = to;
    }

    public void setDefaults() {
    }
}
