package org.owntracks.android.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here

// KEEP INCLUDES END
/**
 * Entity mapped to table "INTERVENTION".
 */
@Entity
public class Intervention {

    @Id
    private Long id;

    @NotNull
    private String comment;
    private Long from;
    private Long to;
    private String type;

    @Generated(hash = 1552697598)
    public Intervention(Long id, @NotNull String comment, Long from, Long to, String type) {
        this.id = id;
        this.comment = comment;
        this.from = from;
        this.to = to;
        this.type = type;
    }

    @Generated(hash = 768626443)
    public Intervention() {
    }

    public Intervention(Long id) {
        this.id = id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @NotNull
    public String getComment() {
        return comment;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setComment(@NotNull String comment) {
        this.comment = comment;
    }

    public Long getFrom() {
        return from;
    }

    public void setFrom(Long from) {
        this.from = from;
    }

    public Long getTo() {
        return to;
    }

    public void setTo(Long to) {
        this.to = to;
    }

    public void setDefaults() {
    }
}
